# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Check styling
      run: dotnet format style --verify-no-changes --verbosity diagnostic
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura --no-build --verbosity normal
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.2
      with:
        reports: CapMan.Tests/coverage.cobertura.xml
        targetdir: docs/coverage
        reporttypes: MarkdownSummaryGithub
    - name: Add Report to PR
      uses: mshick/add-pr-comment@v2
      if: always()
      with:
        message-path: |
          docs/coverage/*.md